language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip3 install -r requirements.txt

# command to run tests
script:
  - pytest
  -coverage run test_hello.py
#Command to use coverage 
after_success:
  - coveralls
